server:
  port: 8080

spring:
  kafka:
    #连接kafka集群
    bootstrap-servers: 192.168.200.130:2181,192.168.200.130:2182,192.168.200.130:2183
    producer:
      #key value的序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #生产每个批次最多放多少条记录
      batch-size: 16384
      #生产者一端总的可用发送缓冲大小，此处设置为32M
      buffer-memory: 33554432

    consumer:
      #key value的反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #消费者组id
      group-id: kenProject
      #如果载kafka中找不到当前消费者的偏移量，则直接将偏移量重置为最早的
      auto-offset-reset: earliest
      #消费者的偏移量是自动提交还是手动提交，此处自动提交偏移量
      enable-auto-commit: true
      #消费者偏移量自动提交的时间间隔
      auto-commit-interval: 1000

